<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Thorn Syntax: version 0.1</string>
	<key>fileTypes</key>
	<array>
		<string>thorn</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\{</string>
	<key>foldingStopMarker</key>
	<string>\bend\b|\}</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>Thorn</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(var|val|fun|object|if|while|for)\b</string>
			<key>name</key>
			<string>keyword.control.thorn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![\d.])\s0x[a-fA-F\d]+|\b\d+(\.\d+)?([eE]-?\d+)?|\.\d+([eE]-?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.thorn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(false|nil|true|_G|_VERSION|math\.(pi|huge))\b|(?&lt;![.])\.{3}(?!\.)</string>
			<key>name</key>
			<string>constant.language.thorn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(self)\b</string>
			<key>name</key>
			<string>variable.language.self.thorn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|%|\*|\/|\^|==?|~=|&lt;=?|&gt;=?|(?&lt;!\.)\.{2}(?!\.)</string>
			<key>name</key>
			<string>keyword.operator.thorn</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.thorn</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.thorn</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.thorn</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.thorn</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.thorn</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.thorn</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.thorn</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.thorn</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(#</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.thorn</string>
				</dict>
			</dict>
			<key>end</key>
			<string>#\)</string>
			<key>name</key>
			<string>comment.block.thorn</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.thorn</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#)(?!\[\[).*$\n?</string>
			<key>name</key>
			<string>comment.line.thorn</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.thorn</string>
	<key>uuid</key>
	<string>C437C621-6165-4B3D-B1B2-6D5A3A92657A</string>
</dict>
</plist>
