#!/bin/bash
../../src/ctc --as_lib io.anita
clang -Wno-ignored-attributes -c io.c -o io.c.bc -emit-llvm -I ../../src/
clang -Wno-ignored-attributes -c file.c -o file.c.bc -emit-llvm -I ../../src/
llvm-link compiled.bc io.c.bc file.c.bc -o libio.bc
